/*exported CELL_EMPTY_FILL_COLOR, CELL_EMPTY_BORDER_COLOR, PLAYER_BLIMP_FILL_COLOR, RAY_DEFAULT_LINE_COLOR,
PLAYER_DIRECTION_LINE_WIDTH, RAY_INTERCEPTED_LINE_COLOR, PLAYER_DIRECTION_LINE_SIZE, RAY_LINE_WIDTH,
UPDATE_MILISECONDS, RAYS_ACTIVE, GAME_CANVAS_SIZE, GRID_DIMENSIONS, CELL_SIZE, NUM_RAYS, FOCAL_LENGTH, 
PLAYER_START_POSITION , PLAYER_SIZE, SHADING_TRANSPARENCY*/

//const UPDATE_MILISECONDS = 10;

//OTHER
const EDITOR_CANVAS_SIZE = { //PIXELS
	x: 400,
	y: 300
};

const GAME_CANVAS_SIZE = {
	x: 600,
	y: 300
};

const SHADING_TRANSPARENCY = 0.4;

//GRID
const GRID_DIMENSIONS = {
	x: 64,
	y: 32
};

const CELL_SIZE = {
	x: 16,
	y: 16
};

const CELL_EMPTY_FILL_COLOR = "#ffffff";    
const CELL_EMPTY_BORDER_COLOR = "#000000";


//PLAYER 
const PLAYER_START_POSITION = {
    x: EDITOR_CANVAS_SIZE.x / 2,
    y: EDITOR_CANVAS_SIZE.y / 2
};

const PLAYER_SIZE = {
    x: 10,
    y: 10
};

const PLAYER_BLIMP_FILL_COLOR = "#0000ff";
const PLAYER_DIRECTION_LINE_WIDTH = 3;
const PLAYER_DIRECTION_LINE_SIZE = 50;

//RAYS
const NUM_RAYS = 200; //columns drawn on game canvas
const FOCAL_LENGTH = (Math.PI / 3); // 60 degrees
const RAY_DEFAULT_LINE_COLOR = "#ff0000";
const RAY_INTERCEPTED_LINE_COLOR = "#afafaf";
const RAY_LINE_WIDTH = 1;